### ISSUE TITLE
Does this project is too simple? You could impelement a project with auto trimap generation?

### ISSUE THREAD

**Issue by ypengit** [lnugraha/trimap_generator#1]
Make an example, like slic algorithm in scikit-image.

**Comment by lnugraha** [comment]
你好，

感謝你的評論跟興趣。我使用trimap是為了幫image matting。所以，程式比較簡單。
但是，既然大家跟這件好像有趣，我可能更新這個repo。

**Comment by ypengit** [comment]
I wrote some code about auo trimap generation with SLIC, which is mentioned in [https://arxiv.org/abs/1707.00333](url). But I think the OTC features of the method is too hard to extract, I only use SLIC to divide the image in 10000 clusters. I suggest that if you want to implement your project, you could do something more complex not only with morphology opreations.

I'm just a researcher interestd in matting. If you want to disscuss more about matting and trimap generation,  please let me know.
