### ISSUE TITLE
Mask confidence and dilation operation

### ISSUE THREAD

**Issue by realczy** [lnugraha/trimap_generator#2]
Hi Inugraha,

It seems that you dilate the input binary mask to generate the trimap. But what if the input mask is not confident enough to be sure foreground? E.g., masks generated by Mask RCNN segmentation sometimes extend outside the ground truth objects. So perhaps shrink the input mask a bit (e.g., erosion operation) as sure foreground before dilation?

**Comment by lnugraha** [comment]
感謝您的評論，我正在查一下關於 image erosion。我以前的目的是取得 surrounding tissue ，不是腫瘤。
更新後，我立即通知您。
FYI, 我把 U-Net 生成 binary images。 根據Jaccard Index的評估，我的score是 0.94/1.00（算是高了）。
